zopefoundation/zope.schema

.coveragerc, .gitignore, .travis.yml, CHANGES.rst, docs/fields.rst, docs/narr.rst, docs/validation.rst, setup.cfg, setup.py, src/zope/schema/_bootstrapfields.py, src/zope/schema/_bootstrapinterfaces.py, src/zope/schema/tests/states.py, src/zope/schema/tests/test__bootstrapfields.py, src/zope/schema/tests/test__bootstrapinterfaces.py, src/zope/schema/tests/test__field.py, src/zope/schema/tests/test_accessors.py, src/zope/schema/tests/test_equality.py, src/zope/schema/tests/test_fieldproperty.py, src/zope/schema/tests/test_interfaces.py, src/zope/schema/tests/test_schema.py, src/zope/schema/tests/test_states.py, src/zope/schema/tests/test_vocabulary.py, tox.ini
Use zope.testrunner because of the namespace package issue on recent versions of Python. 
Enable coverage reporting on Travis.
Run doctests on all versions on Travis. --- This is the WIP part, I haven't run these tests locally yet.
Python 3.3 dropped because Sphinx dropped it.
Fixes #30
=> Add Python 3.6, drop Python 3.3, 100% coverage.

README.rst
=> Point to https://zopeschema.readthedocs.io/ instead of docs.zope.org

docs/fields.rst, src/zope/schema/interfaces.py
There's another typo I saw somewhere, I'll add it to this PR
=> Fixes for #33 (Datetime field docs typo)

CHANGES.rst, src/zope/schema/_bootstrapfields.py, src/zope/schema/tests/test__bootstrapfields.py
They use a defined hashing algorithm that matches what equality does on all versions of Python. Previously, on Python 2, fields were hashed based on their identity. This violated the rule that equal objects should have equal hashes, and now they do. Since having equal hashes does not imply that the objects are equal, this is not expected to be a compatibility problem.
This is an alternative to #38 ; I don't expect that there will be any practical compatibility issues making the fix the way the language spec intends. Included tests with a dict show that there shouldn't be false matches even with equal hashes.
Fixes #36
=> ``Field`` instances are hashable on Python 3

CHANGES.rst, src/zope/schema/interfaces.py, src/zope/schema/tests/test__field.py, src/zope/schema/tests/test_vocabulary.py, src/zope/schema/vocabulary.py
Fixes #15 and fixes #6
I went with backslashreplace because I couldn't find anything that was portable and operated on textual data (binascii and quopri need binary data; namereplace needs Python 3.5+).
The ITerm comment claims that token should be an IASCIILine, which is a native string, not necessarily text, so that's what I kept it here.
Note that we're not actually enforcing that the value is an IASCIILine. Passing in control characters would still be allowed as before.
=> Handle Unicode token values with non-ascii chars.

CHANGES.rst, docs/conf.py, src/zope/schema/_field.py, src/zope/schema/interfaces.py, src/zope/schema/tests/test__field.py, tox.ini
Leave the ability to opt-out of that in case it causes unexpected breakage.
Fixes #10.
@tseaver wrote:
>  I am concerned that obscuring the Invalid eror raised by the invariant check is going to lead to hard-to-debug errors, so I haven't committed the patch. 
In Python 3, each contained `Invalid` exception carries its traceback with it, so perhaps this is much less of a concern than it used to be.
=> Add the ability for Object to check schema invariants.

CHANGES.rst, docs/fields.rst, src/zope/schema/_bootstrapfields.py, src/zope/schema/_bootstrapinterfaces.py, src/zope/schema/_field.py, src/zope/schema/_schema.py, src/zope/schema/interfaces.py, src/zope/schema/tests/test__bootstrapfields.py, src/zope/schema/tests/test__field.py, src/zope/schema/tests/test_schema.py, tox.ini
All of them have a ``field`` and ``value`` now.
For Object fields, introduce a new exception (extending the old exception) to allow distinguishing which fields threw which error and which errors are general validation errors.
Fixes #16
=> Give ValidationErrors more context information.

CHANGES.rst, src/zope/schema/_bootstrapfields.py, src/zope/schema/tests/test__bootstrapfields.py
Fixes #40 
There will be test conflicts with #50. Once either of them is merged I will fix the test conflicts and expand the usage of the EqualityTestsMixin to cover the rest of the fields in the remaining PR.
=> Include a field's interface in equality and hashing.

CHANGES.rst, docs/api.rst, src/zope/schema/__init__.py, src/zope/schema/_bootstrapfields.py, src/zope/schema/_field.py, src/zope/schema/interfaces.py, src/zope/schema/tests/test__bootstrapfields.py, src/zope/schema/tests/test__field.py
In descending order of generality these are ``Number``, ``Complex``, ``Real``, ``Rational`` and ``Integral``. The ``Int`` class extends ``Integral``, the ``Float`` class extends ``Real``, and the
``Decimal`` class extends ``Number``.
Generalize the parsing of numbers in the Number class.
Add tests and document them.
Run the field and bootstrap field doctests as part of unittesting, not just under tox with sphinx, and make them run on both Python 2 and 3.
Fixes #49
One thing I'm not 100% sure of is the order of converters that Number and Complex try. In particular,  is it right to break the rule and mis-order fractions? Practically, that seems like the right choice?
```python
_unicode_converters = (int, float, fractions.Fraction, complex, decimal.Decimal)
```
=> Add fields and interfaces matching the numeric tower.

CHANGES.rst, src/zope/schema/tests/test__field.py, src/zope/schema/tests/test_vocabulary.py, src/zope/schema/vocabulary.py
Fixes #18
Some other vocabulary fixes while I was in there:
- Make TreeVocubalary.fromDict only actually assign titles when a  title is given. This makes it consistent with  `SimpleVocubalary.fromItems()` and make more sense IMO. There were no tests for this, so I added some.
- Give equality and hash methods to `SimpleTerm` and `SimpleVocubalary`.
This was a confusing stumbling block in the implementation of #51.
=> Make SimpleVocabulary.fromItems() accept triples to assign titles

CHANGES.rst, docs/api.rst, src/zope/schema/_bootstrapfields.py, src/zope/schema/tests/test__bootstrapfields.py
Subclasses can extend/override with getExtraDocLines().
Fixes #60.
I went with field lists instead of text to make things prettier and less intrusive.
=> Add more information to fields in getDoc().

CHANGES.rst, src/zope/schema/_bootstrapfields.py, src/zope/schema/_bootstrapinterfaces.py, src/zope/schema/_compat.py, src/zope/schema/_field.py, src/zope/schema/interfaces.py, src/zope/schema/tests/test__bootstrapfields.py, src/zope/schema/tests/test__field.py
As a counterpoint to IFromUnicode.
This is useful when you know the type of data you're dealing with, and conversions are either trivially non-lossy (or will fail anyway) or are not necessary.
The numeric fields as well as Bytes/Line and URI, DottedName and Id implement this, the last three because they are native string lines that want to accept bytes on Python 2 anyway.
On Python 2, lxml likes to produce byte strings "to save memory" even when parsing unicode and given proper XML encoding information, so this can be very helpful there.
This stems from https://github.com/NextThought/nti.externalization/issues/92
=> Add IFromBytes

CHANGES.rst, src/zope/schema/_bootstrapfields.py, src/zope/schema/tests/test__bootstrapfields.py
Fixes #69.
An alternate version of #70 with conflicts resolved and a test case.
=> Fix passing ``None`` as the description to a field constructor.

CHANGES.rst, docs/api.rst, src/zope/schema/__init__.py, src/zope/schema/_field.py, src/zope/schema/interfaces.py, src/zope/schema/tests/test__field.py
Also add a `PythonIdentifier` class, and share the regex for an identifier between `DottedName` and `PythonIdentifier` so they are in sync.
This is to help with https://github.com/zopefoundation/zope.configuration/pull/29 and https://github.com/zopefoundation/zope.configuration/issues/28
=> Make DottedName accept leading underscores.

CHANGES.rst, src/zope/schema/tests/test_vocabulary.py, src/zope/schema/vocabulary.py
This fixes a case that was revealed in Plone tests.
Decoding bytes using raw_unicode_escape and then encoding as ascii with the backslashreplace error handler appears to give something similar to bytes repr without the b'' quotes around it.
=> Fix SimpleTerm token generation from non-ascii bytes value

src/zope/schema/_bootstrapfields.py, src/zope/schema/tests/test__bootstrapfields.py
This fix solves #86, normalization of unicode. Unicode will be normalized to NFC
(Normalization Form Canonical Composition) as long as suppress_unicode_normalization isn't given. This change affects (base-) class Text.
=> Fixing #86 by normalizing unicode for IFromUnicode

.gitignore, .travis.yml, CHANGES.rst, setup.py, src/zope/schema/_field.py, src/zope/schema/accessors.py, src/zope/schema/tests/test__bootstrapfields.py, src/zope/schema/tests/test__field.py, src/zope/schema/tests/test_accessors.py, tox.ini
And test this. Fixes #80.
Add Python 3.8, drop Python 3.4.
=> Make the resolution order of all fields consistent.

src/zope/schema/tests/test_accessors.py
This branch is unused when running tests with zope.interface >= 5.0.1.
=> Restore 100% coverage

CHANGES.rst, src/zope/schema/fieldproperty.py, src/zope/schema/tests/test_fieldproperty.py
Fix FieldUpdateEvent implementation by having an `object` attribute as the `IFieldUpdatedEvent` interfaces claims there should be. Fixes #102
=> IFieldUpdatedEvent not correctly implemented by FieldUpdatedEvent

.gitignore, .meta.toml, setup.cfg, tox.ini
Without the additional ignore `check-manifest` fails when running zest.releasers's `fullrelease` script:
```
missing from sdist:
docs/_static
```
=> Add needed check-manifest ignore

CHANGES.rst, src/zope/schema/_bootstrapfields.py, src/zope/schema/_field.py
Fixes #115 
See https://github.com/python/cpython/issues/95778 for why value sizes were limited in Python.
=> Fix outsized integer test values that break tests on newer Python versions

CHANGES.rst, src/zope/schema/_messageid.py, src/zope/schema/tests/test__messageid.py
I introduced this regression in
https://github.com/zopefoundation/zope.schema/pull/118 by misreading the try/except/else logic in `zope.schema._messageid`.  The new tests should guard against somebody else making a similar mistake in future.
=> Fix fallback when zope.i18nmessageid is not installed
